# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      # # uses the docker miniconda container
      # - uses: docker://continuumio/miniconda

      # Runs a python job
      - name: Run .py File
        uses: actions/checkout@v2
        run: |
          docker pull docker://continuumio/miniconda
          docker run continuumio/miniconda python my_ml_code/ml_prep.py
