# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # builds the docker image with the github repo code included
      - name: Build Docker Image from Dockerfile
        run: | 
              docker build -f infrastructure/DOCKERFILE -t testmini:latest .
              docker run testmini:latest python /portfolio/my_ml_code/ml_prep.py

      - name: Check github environment variables
        run: |
              echo $GITHUB_REPOSITORY
              echo $GITHUB_HEAD_REF
              echo $GITHUB_BASE_REF
